### ISSUE TITLE
"Ending Point" link broken in LearnToEfficientlyTestETLPipelines.md 

### ISSUE THREAD

**Issue by luciancic** [jmasonlee/Talks#1]
Loved your presentation, so I went back to check the talk readme. The "starting point" link points to your [saff_squeezing_pyspark_tests](https://github.com/jmasonlee/saff_squeezing_pyspark_tests) repo, which is great.

The ending point link right now is nothing (automatically links to the Talks repo) but should probably be https://github.com/jmasonlee/saff_squeezing_pyspark_tests/blob/super_clean_test/test/review_count_tests.py

**Comment by jmasonlee** [comment]
Thank you so much! I've updated my links. Hopefully they all work for you now
